name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo mv /var/www/test/ /var/www/testxxx
            cd /home/ubuntu/secretnvp
            git checkout -f 
            git pull origin master
            sudo cp app.tar.gz /var/www/test
            cd /var/www/test
            sudo tar -xf app.tar.gz
            cd ../
            sudo cp -Rf essentials/.env essentials/vendor test
            sudo chown -R www-data:www-data test/
            sudo rm -Rf test/app.tar.gz
      
      - name: testing
        with:
          script: |
            cd /home/ubuntu/
            touch ANOTHER.txt