name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Prepping deployment artifacts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/secretnvp
            git checkout -f 
            git pull origin master
            tar -czf ${{ github.sha }}.tar.gz --exclude=.git --exclude=node_modules *
        
      - name: Backing up and setup for installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/
            sudo rm -Rf *.tar.gz
            NVP_SUFFIX=$(date "+%Y.%m.%d-%H.%M")
            sudo mv test/ test-$NVP_SUFFIX
            sudo tar -cvf test-$NVP_SUFFIX.tar test-$NVP_SUFFIX/
            sudo gzip -9vf test-$NVP_SUFFIX.tar
            sudo rm -Rf test-$NVP_SUFFIX
            sudo mkdir test
            sudo cp -Rf essentials/.env essentials/vendor test

      - name: Installing new files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/secretnvp
            sudo cp -v ${{ github.sha }}.tar.gz /var/www/test
            cd /var/www/test
            sudo tar -xf ${{ github.sha }}.tar.gz
            cd ../
            sudo chown -Rf www-data:www-data test/
      
      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/secretnvp
            rm -Rf *.tar.gz
            cd /var/www/test
            sudo php artisan cache:clear
            sudo php composer dump-autoload
            sudo php artisan config:cache

        