name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # laravel-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Setup .env file
  #     run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
  #   - name: Install Dependencies
  #     run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
  #   - name: Generate key
  #     run: php artisan key:generate
    
  #   - name: Directory Permissions
  #     run: chmod -R 777 storage bootstrap/cache

  deploy:
    runs-on: ubuntu-latest
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu
            touch thetest.txt
            # cd /var/www/secretnvp
            # git checkout -f 
            # git pull origin master